# action.yml
name: 'Dispatch Event'
description: 'this will dispatch a repository event'
inputs:
  github-token:  
    description: 'github-token'
    required: true
    default: 'missing-github-token'
  event-to-dispatch:  
    description: 'event-to-dispatch'
    required: true
    default: 'missing-event-to-dispatch'
outputs:
  result: 
    description: 'The result of the dispatch'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.event-to-dispatch }}