#CI Test. This will pass when the user defined event is trigged by the CI Task
name: name: CI Tests
on:
  repository_dispatch:
    types: [user-defined-event]
jobs:
  shell:
    name: Simple shell to validate repository-dispatch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2   
    - name: Shell test 
      run: |  
        ls -al 

 