#CI Test, phase 1. This test triggers the second workflow
#Only create a badge when the second workflow passes
name: CI-Phase-1 
on: [push] 
jobs:
  test_locally_trigger:
    runs-on: ubuntu-latest
    name: Triggers a workflow via a user-defined-event
    steps: 
      - name: Checkout to test
        uses: actions/checkout@v2
      - name: Run local action
        uses: ./  
        id: dispatch
        with:
          github-token: ${{ secrets.MY_TOKEN }}  
          event-to-dispatch: user-defined-event
      - name: Result from the signal
        run: echo "Result ${{ steps.dispatch.outputs.result }}"